### ISSUE TITLE
QA - SPARK CONNECTOR - errors on connection closing

### ISSUE THREAD

**Issue by Pyrobal** [ActianCorp/spark-vector#28]
latest jar provided by Cristi shows new errors after the unload finished.

by Andrei:
"I think we try to close the connection and it was already closed"

```
  scala> sqlContext.sql("select * from tab_VARCHAR1").write.format("com.databr
```

icks.spark.csv").save(s"$savepath/tab_VARCHAR1.csv")

[Stage 2:==========> (3 + 4)
/ 16]
[Stage 2:=====================> (6 + 4) /
16]
[Stage 2:=============================> (8 + 4) /
16]
[Stage 2:=======================================> (11 + 2) / 1
6]
[Stage 2:==========================================> (12 + 2) / 16
]
[Stage 2:=================================================> (14 + 2) / 16]

[Stage 2:=====================================================> (15 + 1) / 16]

1
6/05/10 13:40:12 ERROR LiveListenerBus: Listener anonfununloadVector1anon1 threw an exception
      java.sql.SQLNonTransientConnectionException: Connection closed.
      at com.ingres.gcf.util.SqlExType.getSqlEx(SqlExType.java:97)
      at com.ingres.gcf.util.SqlExFactory.get(SqlExFactory.java:68)
      at com.ingres.gcf.jdbc.JdbcConn.check(JdbcConn.java:1663)
      at com.ingres.gcf.jdbc.JdbcConn.commit(JdbcConn.java:3162)
      at com.actian.spark_vector.vector.VectorJDBC.commit(VectorJDBC.scala:207)
      at com.actian.spark_vector.datastream.DataStreamClient.commit(DataStreamClient.scala:83)
      at com.actian.spark_vector.vector.Vector$$anonfun$unloadVector$1$$anon$1.onJobEnd(Vector.scala:130)
      at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:36)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:56)
      at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:37)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(AsynchronousListenerBus.scala:79)
      at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1135)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
      16/05/10 13:40:12 ERROR LiveListenerBus: Listener anonfununloadVector1anon1threw an exception
      java.sql.SQLNonTransientConnectionException: Connection closed.
      at com.ingres.gcf.util.SqlExType.getSqlEx(SqlExType.java:97)
      at com.ingres.gcf.util.SqlExFactory.get(SqlExFactory.java:68)
      at com.ingres.gcf.jdbc.JdbcConn.check(JdbcConn.java:1663)
      at com.ingres.gcf.jdbc.JdbcConn.commit(JdbcConn.java:3162)
      at com.actian.spark_vector.vector.VectorJDBC.commit(VectorJDBC.scala:207)
      at com.actian.spark_vector.datastream.DataStreamClient.commit(DataStreamClient.scala:83)
      at com.actian.spark_vector.vector.Vector$$anonfun$unloadVector$1$$anon$1.onJobEnd(Vector.scala:130)
      at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:36)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:56)
      at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:37)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.app
ly$mcV$sp(AsynchronousListenerBus.scala:79)
      at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1135)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)

```
  scala>

  scala> sqlContext.sql(s"""CREATE TEMPORARY TABLE tab_VARCHAR20
       | USING com.actian.spark_vector.sql.DefaultSource
       | OPTIONS (
       | host "$hostname",
       | instance "$installation_ID",
       | database "$databasename",
       | table "tab_VARCHAR20",
       | user "actian",
       | password "actian")""")
  res6: org.apache.spark.sql.DataFrame = []

  scala>

  scala> sqlContext.sql("select * from tab_VARCHAR20").write.format("com.datab
```

ricks.spark.csv").save(s"$savepath/tab_VARCHAR20.csv")

[Stage 3:==============> (4 + 4)
/ 16]
[Stage 3:=====================> (6 + 4) /
16]
[Stage 3:===================================> (10 + 4) /
16]
[Stage 3:==========================================> (12 + 2) / 1
6]
[Stage 3:==============================================> (13 + 2) / 16
]
[Stage 3:=================================================> (14 + 2) / 16]

[Stage 3:=====================================================> (15 + 1) / 16]

1
6/05/10 13:40:16 ERROR LiveListenerBus: Listener anonfununloadVector1anon1 threw a
n exception
      java.sql.SQLNonTransientConnectionException: Connection closed.
      at com.ingres.gcf.util.SqlExType.getSqlEx(SqlExType.java:97)
      at com.ingres.gcf.util.SqlExFactory.get(SqlExFactory.java:68)
      at com.ingres.gcf.jdbc.JdbcConn.check(JdbcConn.java:1663)
      at com.ingres.gcf.jdbc.JdbcConn.commit(JdbcConn.java:3162)
      at com.actian.spark_vector.vector.VectorJDBC.commit(VectorJDBC.scala:207)
      at com.actian.spark_vector.datastream.DataStreamClient.commit(DataStreamClient.scala:83)
      at com.actian.spark_vector.vector.Vector$$anonfun$unloadVector$1$$anon$1.onJobEnd(Vector.scala:130)
      at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:36)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:56)
      at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:37)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.app
ly$mcV$sp(AsynchronousListenerBus.scala:79)
      at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1135)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
      16/05/10 13:40:16 ERROR LiveListenerBus: Listener anonfununloadVector1anon1threw an exception
      java.sql.SQLNonTransientConnectionException: Connection closed.
      at com.ingres.gcf.util.SqlExType.getSqlEx(SqlExType.java:97)
      at com.ingres.gcf.util.SqlExFactory.get(SqlExFactory.java:68)
      at com.ingres.gcf.jdbc.JdbcConn.check(JdbcConn.java:1663)
      at com.ingres.gcf.jdbc.JdbcConn.commit(JdbcConn.java:3162)
      at com.actian.spark_vector.vector.VectorJDBC.commit(VectorJDBC.scala:207)
      at com.actian.spark_vector.datastream.DataStreamClient.commit(DataStreamClient.scala:83)
      at com.actian.spark_vector.vector.Vector$$anonfun$unloadVector$1$$anon$1.onJobEnd(Vector.scala:130)
      at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:36)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:56)
      at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:37)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.app
ly$mcV$sp(AsynchronousListenerBus.scala:79)
      at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1135)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
      16/05/10 13:40:16 ERROR LiveListenerBus: Listener anonfununloadVector1anon1threw an exception
      java.sql.SQLNonTransientConnectionException: Connection closed.
      at com.ingres.gcf.util.SqlExType.getSqlEx(SqlExType.java:97)
      at com.ingres.gcf.util.SqlExFactory.get(SqlExFactory.java:68)
      at com.ingres.gcf.jdbc.JdbcConn.check(JdbcConn.java:1663)
      at com.ingres.gcf.jdbc.JdbcConn.commit(JdbcConn.java:3162)
      at com.actian.spark_vector.vector.VectorJDBC.commit(VectorJDBC.scala:207)
      at com.actian.spark_vector.datastream.DataStreamClient.commit(DataStreamClient.scala:83)
      at com.actian.spark_vector.vector.Vector$$anonfun$unloadVector$1$$anon$1.onJobEnd(Vector.scala:130)
      at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:36)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
      at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:56)
      at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:37)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.app
ly$mcV$sp(AsynchronousListenerBus.scala:79)
      at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1135)
      at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)

```
  scala>
```

**Comment by cbarca** [comment]
some explanation: sparkContext contains the listener(s) to close our datastream client's connections...the thing is we never clean on job restart, thus the (prev)listener remains there (and more are added to the context) making multiple .stop() calls on the client

**Comment by cbarca** [comment]
fixed in external-insert branch, which will soon be merged

**Comment by cbarca** [comment]
fixed in master too, closing
