### ISSUE TITLE
ScanRDD not able to be reused in a subsequent job

### ISSUE THREAD

**Issue by cbarca** [ActianCorp/spark-vector#50]
16/06/03 12:18:31 INFO VectorRelation: Execute Vector prepared query: select code,description from airport
16/06/03 12:18:31 INFO SparkContext: Starting job: rdd at package.scala:148
16/06/03 12:18:31 INFO DAGScheduler: Got job 0 (rdd at package.scala:148) with 1 output partitions
16/06/03 12:18:31 INFO DAGScheduler: Final stage: ResultStage 0 (rdd at package.scala:148)
16/06/03 12:18:31 INFO DAGScheduler: Parents of final stage: List()
16/06/03 12:18:31 INFO DAGScheduler: Missing parents: List()
16/06/03 12:18:31 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[4] at rdd at package.scala:148), which has no missing parents
16/06/03 12:18:32 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 4.9 KB, free 4.9 KB)
16/06/03 12:18:32 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 2.6 KB, free 7.4 KB)
16/06/03 12:18:32 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:53108 (size: 2.6 KB, free: 257.9 MB)
16/06/03 12:18:32 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1006
16/06/03 12:18:32 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[4] at rdd at package.scala:148)
16/06/03 12:18:32 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks
16/06/03 12:18:32 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,NODE_LOCAL, 1925 bytes)
16/06/03 12:18:32 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/06/03 12:18:33 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 511379 bytes result sent to driver
16/06/03 12:18:34 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1544 ms on localhost (1/1)
16/06/03 12:18:34 INFO DAGScheduler: ResultStage 0 (rdd at package.scala:148) finished in 1.607 s
16/06/03 12:18:34 INFO DAGScheduler: Job 0 finished: rdd at package.scala:148, took 2.254277 s
16/06/03 12:18:34 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
16/06/03 12:18:34 INFO deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
16/06/03 12:18:34 INFO deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
16/06/03 12:18:34 INFO deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
16/06/03 12:18:34 INFO deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
16/06/03 12:18:34 INFO deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
16/06/03 12:18:35 INFO SparkContext: Starting job: saveAsTextFile at package.scala:179
16/06/03 12:18:35 INFO DAGScheduler: Registering RDD 5 (rdd at package.scala:148)
16/06/03 12:18:35 INFO DAGScheduler: Got job 1 (saveAsTextFile at package.scala:179) with 2 output partitions
16/06/03 12:18:35 INFO DAGScheduler: Final stage: ResultStage 2 (saveAsTextFile at package.scala:179)
16/06/03 12:18:35 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 1)
16/06/03 12:18:35 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 1)
16/06/03 12:18:35 INFO DAGScheduler: Submitting ShuffleMapStage 1 (MapPartitionsRDD[5] at rdd at package.scala:148), which has no missing parents
16/06/03 12:18:35 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 8.0 KB, free 15.4 KB)
16/06/03 12:18:35 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 4.3 KB, free 19.7 KB)
16/06/03 12:18:35 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on localhost:53108 (size: 4.3 KB, free: 257.9 MB)
16/06/03 12:18:35 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1006
16/06/03 12:18:35 INFO DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 1 (MapPartitionsRDD[5] at rdd at package.scala:148)
16/06/03 12:18:35 INFO TaskSchedulerImpl: Adding task set 1.0 with 1 tasks
16/06/03 12:18:35 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, localhost, partition 0,NODE_LOCAL, 1914 bytes)
16/06/03 12:18:35 INFO Executor: Running task 0.0 in stage 1.0 (TID 1)
16/06/03 12:18:35 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)
java.lang.Exception: Connection to Vector end point has been closed or amount of data communicated does not match the message length
            at com.actian.spark_vector.datastream.reader.DataStreamReader$$anonfun$readByteBuffer$1.apply(DataStreamReader.scala:96)
            at com.actian.spark_vector.datastream.reader.DataStreamReader$$anonfun$readByteBuffer$1.apply(DataStreamReader.scala:88)
            at com.actian.spark_vector.util.ResourceUtil$.closeResourceOnFailure(ResourceUtil.scala:39)
            at com.actian.spark_vector.datastream.reader.DataStreamReader$.readByteBuffer(DataStreamReader.scala:88)
            at com.actian.spark_vector.datastream.reader.DataStreamReader$.readByteBufferWithLength(DataStreamReader.scala:106)
            at com.actian.spark_vector.datastream.reader.DataStreamReader$.readWithByteBuffer(DataStreamReader.scala:113)
            at com.actian.spark_vector.srp.VectorSRPClient.authenticate(VectorSRPClient.scala:98)
            at com.actian.spark_vector.datastream.DataStreamConnector$$anonfun$openSocketChannel$1.apply$mcV$sp(DataStreamConnector.scala:96)
            at com.actian.spark_vector.datastream.DataStreamConnector$$anonfun$openSocketChannel$1.apply(DataStreamConnector.scala:96)
            at com.actian.spark_vector.datastream.DataStreamConnector$$anonfun$openSocketChannel$1.apply(DataStreamConnector.scala:96)
            at com.actian.spark_vector.util.ResourceUtil$.closeResourceOnFailure(ResourceUtil.scala:39)
            at com.actian.spark_vector.datastream.DataStreamConnector.openSocketChannel(DataStreamConnector.scala:96)
            at com.actian.spark_vector.datastream.DataStreamConnector.newConnection(DataStreamConnector.scala:108)
            at com.actian.spark_vector.datastream.reader.DataStreamReader.read(DataStreamReader.scala:47)
            at com.actian.spark_vector.vector.Vector$$anonfun$unloadVector$1$$anonfun$7.apply(Vector.scala:124)
            at com.actian.spark_vector.vector.Vector$$anonfun$unloadVector$1$$anonfun$7.apply(Vector.scala:124)
            at com.actian.spark_vector.datastream.reader.ScanRDD.compute(ScanRDD.scala:44)
            at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
            at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
            at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
            at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
            at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
            at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
            at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
            at org.apache.spark.scheduler.Task.run(Task.scala:89)
            at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
16/06/03 12:18:35 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 1, localhost): java.lang.Exception: Connection to Vector end point has been closed or amount of data communicated does not match the message length
            at com.actian.spark_vector.datastream.reader.DataStreamReader$$anonfun$readByteBuffer$1.apply(DataStreamReader.scala:96)
            at com.actian.spark_vector.datastream.reader.DataStreamReader$$anonfun$readByteBuffer$1.apply(DataStreamReader.scala:88)
            at com.actian.spark_vector.util.ResourceUtil$.closeResourceOnFailure(ResourceUtil.scala:39)
            at com.actian.spark_vector.datastream.reader.DataStreamReader$.readByteBuffer(DataStreamReader.scala:88)
            at com.actian.spark_vector.datastream.reader.DataStreamReader$.readByteBufferWithLength(DataStreamReader.scala:106)
            at com.actian.spark_vector.datastream.reader.DataStreamReader$.readWithByteBuffer(DataStreamReader.scala:113)
            at com.actian.spark_vector.srp.VectorSRPClient.authenticate(VectorSRPClient.scala:98)
            at com.actian.spark_vector.datastream.DataStreamConnector$$anonfun$openSocketChannel$1.apply$mcV$sp(DataStreamConnector.scala:96)
            at com.actian.spark_vector.datastream.DataStreamConnector$$anonfun$openSocketChannel$1.apply(DataStreamConnector.scala:96)
            at com.actian.spark_vector.datastream.DataStreamConnector$$anonfun$openSocketChannel$1.apply(DataStreamConnector.scala:96)
            at com.actian.spark_vector.util.ResourceUtil$.closeResourceOnFailure(ResourceUtil.scala:39)
            at com.actian.spark_vector.datastream.DataStreamConnector.openSocketChannel(DataStreamConnector.scala:96)
            at com.actian.spark_vector.datastream.DataStreamConnector.newConnection(DataStreamConnector.scala:108)
            at com.actian.spark_vector.datastream.reader.DataStreamReader.read(DataStreamReader.scala:47)
            at com.actian.spark_vector.vector.Vector$$anonfun$unloadVector$1$$anonfun$7.apply(Vector.scala:124)
            at com.actian.spark_vector.vector.Vector$$anonfun$unloadVector$1$$anonfun$7.apply(Vector.scala:124)
            at com.actian.spark_vector.datastream.reader.ScanRDD.compute(ScanRDD.scala:44)
            at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
            at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
            at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
            at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
            at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
            at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
            at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
            at org.apache.spark.scheduler.Task.run(Task.scala:89)
            at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)

**Comment by cbarca** [comment]
a "select col from table order by 1" triggers 2x jobs (one after the other, a Map and then a Shuffle)

**Comment by cbarca** [comment]
The VectorEndpoints _and their roles_ are used more than the assigned list:

16/06/06 18:35:29 INFO ParseDriver: Parsing command: select \* from airport order by 1
16/06/06 18:35:30 INFO ParseDriver: Parse Completed
ret: org.apache.spark.sql.DataFrame = [code: int, desc: string]

scala> ret.collect
16/06/06 18:35:35 INFO VectorRelation: Execute Vector prepared query (1): select code,desc from airport
16/06/06 18:35:35 DEBUG VectorEndpoint: Running sql query select host, port, username, password from iivwtable_datastreams to get the datastream endpoints' info.
16/06/06 18:35:35 DEBUG VectorEndpoint: Got the following VectorEndPoints from the datastreams table: VectorEndpoint(nlam-cluster01,37355,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(nlam-cluster01,37355,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER05,26513,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER05,26513,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER04,25901,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER04,25901,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER06,44047,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER06,44047,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER03,58488,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER03,58488,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER02,54728,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455),VectorEndpoint(NLAM-CLUSTER02,54728,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455)
16/06/06 18:35:35 DEBUG DataStreamClient: Got 12 datastreams

stderr log page for app-20160606183347-0033/2 :
16/06/06 18:35:40 DEBUG DataStreamConnector: Opening a socket to VectorEndpoint(NLAM-CLUSTER02,54728,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455) for partition 10
16/06/06 18:35:42 DEBUG DataStreamConnector: Opening a socket to VectorEndpoint(NLAM-CLUSTER02,54728,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455) for partition 11

stderr log page for app-20160606183347-0033/1 : 
16/06/06 18:35:42 DEBUG DataStreamConnector: Opening a socket to VectorEndpoint(NLAM-CLUSTER02,54728,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455) for partition 10

stderr log page for app-20160606183347-0033/3 : 
16/06/06 18:35:39 DEBUG DataStreamConnector: Opening a socket to VectorEndpoint(NLAM-CLUSTER02,54728,ds16_18633135571568977849,160C7CCF1E9C74064165CF6A61F80E7135F32A6C76AA8860363E231737157455) for partition 11
